version: "3.6"

services:
  frps:
    image: registry.cn-shenzhen.aliyuncs.com/nekoimi/frp:server
    volumes:
      - "./frps.ini:/frps.ini"
      - "./404.html:/404.html"
    restart: always
    privileged: true
    network_mode: host
